"""
Split claims into Tier A (objective consensus -> truth-labelable) and
Tier B (opinion / contested / temporal -> no truth label; judged on whether
the system correctly expresses division/uncertainty).

Output: tiers.json  { claim: {tier:"A"|"B", truth: true|false|null, note:str, reviewed:false} }

This is a STARTING POINT generated by substring rules. REVIEW every row, especially
those with a note. Tier A truth drives verdict-accuracy scoring; Tier B is excluded
from accuracy and scored only on uncertainty calibration. Edit freely.

Re-run:  python gen_tiers.py [labeled_sources.json]
"""
import json, sys

TIER_A_FALSE = ["5g causes covid","5g towers cause cancer","einstein failed math",
    "bats are blind","bulls are enraged","columbus discovered","cracking your knuckles",
    "dogs can only see","drinking bleach","carrots improves your eyesight","goldfish",
    "10 percent of their brain","10% of our brains","lemmings","lightning never strikes",
    "shaving makes hair","sugar makes children","great wall","sahara desert is the largest",
    "body temperature is 98.6","earth is flat","moon landing was faked","vaccines cause autism",
    "video games cause","violent video games","msg is dangerous","amazon rainforest produces"]
TIER_A_TRUE = ["antibiotics do not work against viruses","climate change is caused by human",
    "climate change is real","evolution is real","honey never expires","98% of dna",
    "octopuses have three hearts","smoking causes lung cancer","earth revolves around the sun",
    "speed of light is constant","sun is a star","water boils at 100"]
TIER_B = ["ai will replace","largest economy","greatest basketball","capitalism is better",
    "cats are better","college education is worth","cryptocurrency","democracy is the best",
    "immigration is good for the economy","inflation in the united states","nuclear energy is safe",
    "organic food is healthier","remote work is more productive","social media is harmful",
    "sugar is worse than fat","greatest band","economy is in a recession","pineapple belongs",
    "universal basic income"]
NOTE = {"msg is dangerous":"consensus: safe in normal amounts, but publicly contested",
    "amazon rainforest produces":"'20%/lungs of earth' figure is debunked/debated",
    "great wall":"visible-from-space is false; phrasing nuance",
    "columbus discovered":"'discovered' framing contested",
    "speed of light is constant":"true in vacuum (nuance)",
    "water boils at 100":"true at sea level (nuance)",
    "body temperature is 98.6":"closer to ~98.2F; outdated"}

def classify(claim: str):
    c = claim.lower()
    for s in TIER_A_FALSE:
        if s in c: return ("A", False, NOTE.get(s, ""))
    for s in TIER_A_TRUE:
        if s in c: return ("A", True, NOTE.get(s, ""))
    for s in TIER_B:
        if s in c: return ("B", None, NOTE.get(s, ""))
    return ("B", None, "UNCLASSIFIED - REVIEW")

def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "/mnt/user-data/uploads/labeled_sources.json"
    rows = json.load(open(path)); claims = sorted(set(r["claim"] for r in rows))
    out = {}; a=b=0
    for c in claims:
        t, truth, note = classify(c)
        out[c] = {"tier": t, "truth": truth, "note": note, "reviewed": False}
        if t == "A": a += 1
        else: b += 1
    json.dump(out, open("tiers.json", "w"), indent=2)
    print(f"Tier A (truth-labelable): {a}   Tier B (uncertainty-judged): {b}")
    print("\nRows with notes / unclassified (review these):")
    for c, v in out.items():
        if v["note"]:
            tr = {True:"TRUE", False:"FALSE", None:"--"}[v["truth"]]
            print(f"  [{v['tier']}/{tr:>5}] {c[:50]:<50} {v['note']}")
    print("\nWrote tiers.json")

if __name__ == "__main__":
    main()
